services:
  # Combined frontend and backend service
  - type: web
    name: bionexa
    env: node
    plan: free
    buildCommand: npm install && npm run build && cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: HMS_ACCESS_KEY
        sync: false
      - key: HMS_SECRET_KEY
        sync: false
      - key: HMS_MANAGEMENT_TOKEN
        sync: false
    healthCheckPath: /api/test 